[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
todo_app = "79Vi6MSmxMrgv9oWqEYbijN8j9gZacbvZHo9nqZQFFxv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/trankhacvy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/create-profile.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/create-todo.ts"
